# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/fused_mult/fused_mult.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fused_mult || ORIG_REF_NAME==fused_mult} -quiet] -quiet
